volumes:
  pg_cas_servis_db:
    name: pg_cas_servis_db
  postgres_data:
    name: postgres_data

services:
  cas_servis_db:
    image: postgres
    restart: always
    container_name: postgres_container
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data